google-deepmind/formal-conjectures

AUTHORS
FormalConjectures/Mathoverflow/486451.lean

[A question by myself](https://mathoverflow.net/questions/486451). The first part is implied to be solved in the literature, but no example or proof is given, and I can't reach the authors. The second part is new as far as I know.

MO question: right local semirings

---

AUTHORS
FormalConjectures/ErdosProblems/499.lean

I haven't yet added the chain of implications for these

feat: formalize erdos 499

---

FormalConjectures/ErdosProblems/316.lean

The statement of Erdos 316 was mis-negated in #68. This PR fixes that, and to confirm the new statement is correct, proves the new statement.

chore: fix statement of erdos 316

---

FormalConjectures/Wikipedia/CollatzConjecture.lean

Formalize Collatz conjecture statement

---

FormalConjectures/ErdosProblems/325.lean

Co-authored-by: bhavikmehta@google.com

add erdos 325

---

FormalConjectures/ErdosProblems/289.lean

Co-authored-by: bhavikmehta@google.com

add erdos 289

---

FormalConjectures/Wikipedia/BatemanHornConjecture.lean

This was an experiment in how hard it is to take a well-known (but not entirely trivial to state) conjecture (from, say, wikipedia), and ask an LLM (in this case, Claude 4.0) to formalize the statement. There was a little cleaning to do (which likely could've been accomplished with more prompting), but it basically one-shot it.

Add Bateman-Horn Conjecture

---

FormalConjectures/Wikipedia/BatemanHornConjecture.lean

Thanks to Will Sawin for pointing out that both Claude and I missed division by the product of degrees in the constant!

Fix: Bateman-Horn Conjecture

---

FormalConjectures/Wikipedia/Grimm.lean

I'm not sure about the `IsSetOfPrimes` approach.

Add Grimm's conjecture

---

FormalConjectures/ErdosProblems/645.lean

Co-authored-by: Bhavik Mehta <bhavikmehta8@gmail.com>

Erdős Problem 645

---

FormalConjectures/Wikipedia/RegularPrimes.lean

Add the conjecture that there are infinitely many regular primes.
closes #246

Regular primes conjecture

---

FormalConjectures/ErdosProblems/17.lean

Formalize Erdos 17

---

AUTHORS
FormalConjectures/Wikipedia/Kakeya.lean

Add Kakeya problem

---

FormalConjectures/ErdosProblems/56.lean

The pairwise coprime condition in the definition of `WeaklyDivisible` should only be applied to members of the set `s`.
Also remove the need for `open Classical` in `MaxWeaklyDivisible`

Fix formalisation of `WeaklyDivisible`

---

FormalConjectures/ErdosProblems/541.lean

feat: add Erdos 541

---

FormalConjectures/Mathoverflow/100324.lean

An integer `n` is a sum of three cubes of integers iff `n` is not 4 or 5 mod 9.

Sum of three cubes

---

FormalConjectures/ErdosProblems/198.lean
FormalConjectures/ForMathlib/Combinatorics/Basic.lean

refactor Sidon set definition

---

FormalConjectures/ErdosProblems/689.lean

feat: formalize Erdos Problem 689

---

FormalConjectures/Wikipedia/FibonacciPrimes.lean

Also restructure documentation a bit.

Variant for infinitude of Fibonacci primes.

---

FormalConjectures/ErdosProblems/128.lean

Erdős Problem 128

---

FormalConjectures/ErdosProblems/416.lean

Feat: add formal statement for Erdos 416

---

FormalConjectures/ErdosProblems/137.lean

Erdős problem 137

---

FormalConjectures/Wikipedia/AgohGiuga.lean

Proof adapted from AlphaProof.

Proof of Korselt's Criterion

---

FormalConjectures/ErdosProblems/845.lean

add `erdos_845`

---

FormalConjectures/ErdosProblems/347.lean

feat: formalise erdos_347

---

FormalConjectures/ErdosProblems/203.lean

Erdős Problem 203

---

FormalConjectures/ErdosProblems/938.lean

Erdős Problems 938

---

FormalConjectures/ErdosProblems/39.lean

Erdős Problem 39

---

FormalConjectures/Wikipedia/InscribedSquare.lean

One more solved special case of the inscribed square problem that was added in #451. See the review comments there.

Inscribed square problem addendum

---

FormalConjectures/ErdosProblems/340.lean
FormalConjectures/ForMathlib/Combinatorics/Basic.lean

add `erdos_340`

---

FormalConjectures/ErdosProblems/155.lean

Erdős Problem 155

---

FormalConjectures/ErdosProblems/160.lean

Erdős Problem 160

---

FormalConjectures/ErdosProblems/12.lean

feat: Add extra variants for erdos_12

---

FormalConjectures/ErdosProblems/358.lean

Feat: add formalisation of Erdős Problem 358 and variants

---

FormalConjectures/ErdosProblems/196.lean

Adding [Erdős 196](https://www.erdosproblems.com/196) . 
Closes #417.

 Feat: Erdős 196

---

FormalConjectures/ErdosProblems/354.lean

feat: Erdős Problem 354

---

FormalConjectures/ErdosProblems/74.lean

Erdős Problem 74

---

FormalConjectures/ErdosProblems/138.lean
FormalConjectures/ForMathlib/Combinatorics/AP/Basic.lean

Erdős Problem 138

---

AUTHORS
FormalConjectures/ErdosProblems/1003.lean

Adds [Erdős Problem 1003](https://www.erdosproblems.com/1003).

Erdős Problem 1003
