FormalConjectures/Wikipedia/LehmerTotient.lean

hello! this PR adds the [Lehmer totient problem](https://en.wikipedia.org/wiki/Lehmer%27s_totient_problem) under `formal-conjectures/FormalConjectures/Wikipedia/LehmerTotient.lean` (closes issue #90), theorem uses sorry (unsolved question for benchmarking), included license header, import, docstrings, and @[category research open, AMS 11]. Builds with `lake build`. Please take a loot at the last commit: `feat: formalise Lehmer totient` :)

feat: formalise Lehmer totient

---

FormalConjectures/ErdosProblems/326.lean
FormalConjectures/ErdosProblems/868.lean
FormalConjectures/ForMathlib/Combinatorics/Additive/Basis.lean
FormalConjectures/ForMathlib/Order/Filter/Cofinite.lean
FormalConjectures/Util/ForMathlib.lean

Adding `Erdos 326`. After formalizing, it was pointed out to me that `Erdos 868` also develops similar API, so this has been abstracted and put into `ForMathlib`.

feat(Erdos/326): add Erdos 326 and abstract some API to ForMathlib

---

FormalConjectures/Wikipedia/Kaplansky.lean

Fix the statement of `counter_unit_conjecture`, which didn't include `K : Type` in the existential, so it's using the K in the variables and claiming the same field K could have any characteristic.
Expand the scope of `omit hG` so `G` doesn't get included in the later statements.
Prove implications between the counter statements.

fix: Kaplansky's conjectures

---

FormalConjectures/Wikipedia/ModularityConjecture.lean

State the Shimura--Taniyama--Weil conjecture  (also known as the modularity conjecture/theorem) for elliptic curves over the rational numbers. 
https://en.wikipedia.org/wiki/Modularity_theorem
This is a very hard, known theorem in the case of the rational number and many  other cases, but open in general (and much harder to state!). The version we state is stronger than what is needed for FLT.
* ams-11

Add Modularity Conjecture 

---

FormalConjectures/Wikipedia/EllipticCurveRank.lean

+ Fix a potential issue when the height bound `H` is 1 in which case `H ^ _` is always 1.
+ Add the asymptotics of `(heightLE H).ncard` as a sanity check.

fix(EllipticCurveRank): corner cases and a sanity check

---

AUTHORS
FormalConjectures/Other/BeaverMathOlympiad.lean

This PR adds the current [Beaver Math Olympiad problems](https://wiki.bbchallenge.org/wiki/Beaver_Math_Olympiad#5._1RB0LD_1LC0RA_1RA1LB_1LA1LE_1RF0LC_---0RE_(bbch)) to the project (see #230).
A few notes:
- I have added verbose comments documenting each problem and crediting the bbchallenge contributors who found the associated TMs and mathematical reformulations
- I have used a lean parenthesisation style that is slightly more verbose than was originally done to help non-native lean speakers
- [BMO#4](https://wiki.bbchallenge.org/wiki/Beaver_Math_Olympiad#4._1RB3RB---1LB0LA_2LA4RA3LA4RB1LB_(bbch)) original formulation is based on a partial definition of `a` I have taken the liberty of making it total through the `else` branch
- In BMO#5 statement, I've used [global definition of function …

Beaver Math Olympiad problems

---

FormalConjectures/ErdosProblems/1.lean
FormalConjectures/ErdosProblems/285.lean
FormalConjectures/ErdosProblems/319.lean
FormalConjectures/ErdosProblems/442.lean
FormalConjectures/ErdosProblems/786.lean
FormalConjectures/ErdosProblems/897.lean

This PR standardizes the use of Landau notation for functions that are `o(1)` or `O(1)`.

Standardize use of Landau notation

---

FormalConjectures/ErdosProblems/143.lean

The sum should be over `A`, where previously it was over `ℕ`. In particular $\sum_{n = 2}^{\infty} \frac{1}{n \log n}$ diverges.

Fix formalisation of `erdos_143.parts.ii`

---

.github/workflows/build-and-docs.yml
docbuild/scripts/overwrite_index.lean
docbuild/scripts/plot_growth.py

- Script for generating plotly graph counting number of files per commit since release date `docbuild/scripts/file_growth.py`
- Modify `docbuild/scripts/overwrite_index.lean` to read in generated graph and inject to the statistics page in the docs
- Add script generation job to GitHub workflow before doc homepage is overwritten

Add file growth plot to documentation front page

---

FormalConjectures/ForMathlib/Combinatorics/SimpleGraph/GraphConjectures/Definitions.lean
FormalConjectures/ForMathlib/Combinatorics/SimpleGraph/GraphConjectures/Domination.lean
FormalConjectures/ForMathlib/Combinatorics/SimpleGraph/GraphConjectures/Invariants.lean
FormalConjectures/Util/ForMathlib.lean
FormalConjectures/WrittenOnTheWallII/GraphConjecture1.lean
FormalConjectures/WrittenOnTheWallII/GraphConjecture19.lean
FormalConjectures/WrittenOnTheWallII/GraphConjecture2.lean
FormalConjectures/WrittenOnTheWallII/GraphConjecture3.lean
FormalConjectures/WrittenOnTheWallII/GraphConjecture34.lean
FormalConjectures/WrittenOnTheWallII/GraphConjecture4.lean
FormalConjectures/WrittenOnTheWallII/GraphConjecture40.lean
FormalConjectures/WrittenOnTheWallII/GraphConjecture5.lean
FormalConjectures/WrittenOnTheWallII/GraphConjecture58.lean
FormalConjectures/WrittenOnTheWallII/GraphConjecture6.lean

We never want to include `FormalConjectures.Util.ProblemImports` inside of `ForMathlib`, but rather the other way around.

clean up imports for WrittenOnTheWallII

---

FormalConjectures/ErdosProblems/672.lean
FormalConjectures/ForMathlib/Combinatorics/AP/Basic.lean

- Also exclude the empty set as a trivial AP in `Set.IsAPOfLengthFree`
- Remove unnecessary `s.Nonempty` in `Erdos672With`

make non-triviality consistent in `Set.IsAPOfLengthFree`

---

FormalConjectures/Wikipedia/LehmerMahlerMeasureProblem.lean

- `Polynomial.HasOddCoeffs` should quantify only over the support of the polynomial, as the coefficients are zero elsewhere. 
- Rename `AllCoeffsOdd` -> `Polynomial.HasOddCoeffs`

fix: definition of `Polynomial.HasOddCoeffs` 

---

FormalConjectures/ErdosProblems/245.lean

`limsup` returns `0` for unbounded sequences when the type of the sequence is `Real`, which leads to false counterexamples in `erdos_245`. AlphaProof found a disproof using the set `S = {2^n}` which is sparse enough to satisfy the conditions of the problem, but `|(S + S) ∩ [1, n] |/|S ∩ [1, n]|` is unbounded.

fix: typing in `erdos_245`  to `EReal`.

---

FormalConjectures/ErdosProblems/168.lean

In `F_eq_card`, maximality is formalised with respect to inclusion but it should be formalised with respect to cardinality since `F` is defined as the max cardinality. In particular, `{1, 2, 5, 6, 7}` is a subset of `{1, ..., 7}` that is maximal with respect to inclusion, but `{1, 3, 4, 5, 6, 7}` is a larger set that contains no AP of the form `n, 2n, 3n` (disproof found by AlphaProof).

fix: maximality in `168.lean`

---

FormalConjectures/Util/Linters/AMSLinter.lean
FormalConjectures/Util/Linters/CategoryLinter.lean
FormalConjectures/Util/Linters/CategoryLinterTest.lean
FormalConjectures/Util/Linters/CopyrightLinter.lean

This PR improves the warning messages from the category and AMS tag linters and prevents the header linter from firing on the file `FormalConjectures.All`.

feat: Improve linter warnings 

---

FormalConjectures/Mathoverflow/34145.lean

golfed proof for `lbMeasure_rigidMotion` adapted from AlphaProof's solution

golf proof for `lbMeasure_rigidMotion`

---

FormalConjectures/ForMathlib/Geometry/3d.lean

This PR preemptively adds the file `ForMathlib/Geometry/3d.lean` as this will most likely be useful in the future.

feat(ForMathlib/Geometry/3d): Add 3-dimensional euclidean space notation & orientation lemmas

---

FormalConjectures/Wikipedia/GaussCircleProblem.lean

As formalised this fails, e.g., for `r = 1/16`.

fix: `error_le` is not true for `r` close to `0`

---

FormalConjectures/Arxiv/1506.05785/MaximumAngle.lean

- If we allow `k = 0` this gives an easy solution of `conjecture_3_4` because then we only have to find a unit vector `b` with `⟪a, b⟫ ≥ 0`.
- The `IsZLattice` instance does not seem to be needed.
- Styling fixes.

fix: `k` should be non-zero in `conjecture_3_4`

---

FormalConjectures/ErdosProblems/155.lean
FormalConjectures/ErdosProblems/30.lean
FormalConjectures/ErdosProblems/329.lean
FormalConjectures/ErdosProblems/340.lean
FormalConjectures/ErdosProblems/44.lean
FormalConjectures/ErdosProblems/707.lean
FormalConjectures/ForMathlib/Combinatorics/Basic.lean

Redefine `IsSidon` for any type `S` with the membership property. This allows `IsSidon A` to work when `A` is a `Finset` without having to write `A.toSet`.

Abstract `IsSidon` 

---

FormalConjectures/ErdosProblems/846.lean
FormalConjectures/ForMathlib/Data/Set/Triplewise.lean
FormalConjectures/Util/ForMathlib.lean

Add definition of `Set.Triplewise` and `Triplewise` to `ForMathlib`.
Co-authored-by: Lawrence Wu <llwu@google.com>
Co-authored-by: Oliver Nash <ddojsioc@google.com>

feat: Add `Set.Triplewise` API

---

FormalConjectures/ErdosProblems/828.lean

Adds [Erdős Problem 828](https://www.erdosproblems.com/828).
Though the site specifies _a_ to be an integer, the original problem does not specify this ([link](https://users.renyi.hu/~p_erdos/1983-27.pdf)). I elected to make it a natural number to avoid coercions with the totient function.

Erdős Problem 828

---

FormalConjectures/Wikipedia/FeitThompsonPrimeConjecture.lean

The Feit-Thompson conjecture for primes is an open problem: https://en.wikipedia.org/wiki/Feit%E2%80%93Thompson_conjecture
This is issue https://github.com/google-deepmind/formal-conjectures/issues/546

Add the Feit-Thompson conjecture for primes to the wikipedia problems

---

FormalConjectures/ErdosProblems/361.lean

The statement "depends irregularly on `n`" seems a little tricky to formalise:)
Fixes #512

feat: Erdős Problem 361

---

FormalConjectures/ErdosProblems/218.lean
FormalConjectures/ErdosProblems/233.lean
FormalConjectures/ErdosProblems/470.lean
FormalConjectures/ForMathlib/NumberTheory/PrimeGap.lean
FormalConjectures/Util/ForMathlib.lean

Adds [Erdős Problem 470](https://www.erdosproblems.com/470)
This PR also moves the definition of `primeGap` to its own separate file under `FormalConjectures/ForMathlib/NumberTheory/PrimeGap.lean` since this problem also uses the definition.

Erdős Problem 470

---

FormalConjectures/Wikipedia/SquarePacking.lean

This PR adds some theorems on square packing described in #646. In particular it has a problem about the minimum size of a square in which 17 unit squares can be packed.

feat(SquarePacking): add formalization of square packing theorems
